### PR TITLE
Added MoonScript version of library and example

### PR DESCRIPTION
**Pull request by c0d3rman**
Added a MoonScript version of deepqlearn.lua and test.lua for ease of reading and modification.
GPU compatible version in the works.

### CODE REVIEW

**Comment by c0d3rman** [comment]
Bug found: functions like randf aren't global, which breaks test.lua.
Fixing it now.

**Comment by c0d3rman** [comment]
Fixed some bugs - ready for merge.

**Comment by blakeMilner** [comment]
Wow, nice change. Mind if I ask what you're trying to do with this code?

**Comment by c0d3rman** [comment]
I'm just messing around with Q-Learning and AI.
I translated it to MoonScript so I could edit it more easily and see what changes.
I'm currently testing my single-GPU version, which seems to be 10% faster. Working on a multi-gpu version.

**Pull request merged**
